#!/usr/bin/env node

var program = require('commander');
var lib = require('./index');
var path = require('path');

program
  .version('0.0.1')
  .option('', '')
  .option('', '')
  .parse(process.argv);

lib.createSite(path.join(program.args[0], '/layouts/default.html'),
path.join(program.args[0], '/pages'), program.args[1],
function(err) {if (err) { throw err; }});
